export interface PaintColor {
  name: string;
  hex: string;
  category: string;
}

export const PAINT_COLORS: PaintColor[] = [
  { name: 'Pure White', hex: '#FFFFFF', category: 'Whites' },
  { name: 'Ivory', hex: '#FFFFF0', category: 'Whites' },
  { name: 'Cream', hex: '#FFFDD0', category: 'Whites' },
  { name: 'Pearl', hex: '#F0EAD6', category: 'Whites' },
  { name: 'Linen', hex: '#FAF0E6', category: 'Whites' },
  { name: 'Snow', hex: '#FFFAFA', category: 'Whites' },
  { name: 'Seashell', hex: '#FFF5EE', category: 'Whites' },
  { name: 'Alabaster', hex: '#F2F0E6', category: 'Whites' },
  { name: 'Antique White', hex: '#FAEBD7', category: 'Whites' },
  { name: 'Vanilla', hex: '#F3E5AB', category: 'Whites' },

  { name: 'Beige', hex: '#F5F5DC', category: 'Neutrals' },
  { name: 'Sand', hex: '#F4A460', category: 'Neutrals' },
  { name: 'Tan', hex: '#D2B48C', category: 'Neutrals' },
  { name: 'Taupe', hex: '#B38B6D', category: 'Neutrals' },
  { name: 'Khaki', hex: '#C3B091', category: 'Neutrals' },
  { name: 'Wheat', hex: '#F5DEB3', category: 'Neutrals' },
  { name: 'Bisque', hex: '#FFE4C4', category: 'Neutrals' },
  { name: 'Almond', hex: '#EFDECD', category: 'Neutrals' },
  { name: 'Ecru', hex: '#C2B280', category: 'Neutrals' },
  { name: 'Buff', hex: '#F0DC82', category: 'Neutrals' },

  { name: 'Light Gray', hex: '#D3D3D3', category: 'Grays' },
  { name: 'Silver', hex: '#C0C0C0', category: 'Grays' },
  { name: 'Warm Gray', hex: '#A8A8A8', category: 'Grays' },
  { name: 'Dove Gray', hex: '#888888', category: 'Grays' },
  { name: 'Slate Gray', hex: '#708090', category: 'Grays' },
  { name: 'Charcoal', hex: '#36454F', category: 'Grays' },
  { name: 'Graphite', hex: '#383838', category: 'Grays' },
  { name: 'Pewter', hex: '#8D9093', category: 'Grays' },
  { name: 'Ash Gray', hex: '#B2BEB5', category: 'Grays' },
  { name: 'Cool Gray', hex: '#8C92AC', category: 'Grays' },
  { name: 'Storm Gray', hex: '#717D7E', category: 'Grays' },
  { name: 'Granite', hex: '#676767', category: 'Grays' },

  { name: 'Powder Blue', hex: '#B0E0E6', category: 'Blues' },
  { name: 'Sky Blue', hex: '#87CEEB', category: 'Blues' },
  { name: 'Light Blue', hex: '#ADD8E6', category: 'Blues' },
  { name: 'Baby Blue', hex: '#89CFF0', category: 'Blues' },
  { name: 'Periwinkle', hex: '#CCCCFF', category: 'Blues' },
  { name: 'Robin Egg', hex: '#00CCCC', category: 'Blues' },
  { name: 'Turquoise', hex: '#40E0D0', category: 'Blues' },
  { name: 'Aqua', hex: '#00FFFF', category: 'Blues' },
  { name: 'Cerulean', hex: '#007BA7', category: 'Blues' },
  { name: 'Azure', hex: '#007FFF', category: 'Blues' },
  { name: 'Cornflower', hex: '#6495ED', category: 'Blues' },
  { name: 'Royal Blue', hex: '#4169E1', category: 'Blues' },
  { name: 'Cobalt', hex: '#0047AB', category: 'Blues' },
  { name: 'Navy Blue', hex: '#000080', category: 'Blues' },
  { name: 'Midnight', hex: '#191970', category: 'Blues' },
  { name: 'Steel Blue', hex: '#4682B4', category: 'Blues' },
  { name: 'Denim', hex: '#1560BD', category: 'Blues' },
  { name: 'Slate Blue', hex: '#6A5ACD', category: 'Blues' },

  { name: 'Mint', hex: '#98FF98', category: 'Greens' },
  { name: 'Seafoam', hex: '#93E9BE', category: 'Greens' },
  { name: 'Sage Green', hex: '#9DC183', category: 'Greens' },
  { name: 'Celery', hex: '#B8C788', category: 'Greens' },
  { name: 'Pistachio', hex: '#93C572', category: 'Greens' },
  { name: 'Sea Green', hex: '#2E8B57', category: 'Greens' },
  { name: 'Jade', hex: '#00A86B', category: 'Greens' },
  { name: 'Olive', hex: '#808000', category: 'Greens' },
  { name: 'Forest Green', hex: '#228B22', category: 'Greens' },
  { name: 'Hunter Green', hex: '#355E3B', category: 'Greens' },
  { name: 'Pine', hex: '#01796F', category: 'Greens' },
  { name: 'Emerald', hex: '#50C878', category: 'Greens' },
  { name: 'Lime', hex: '#C7EA46', category: 'Greens' },
  { name: 'Moss', hex: '#8A9A5B', category: 'Greens' },
  { name: 'Fern', hex: '#4F7942', category: 'Greens' },
  { name: 'Teal', hex: '#008080', category: 'Greens' },

  { name: 'Peach', hex: '#FFE5B4', category: 'Warm Tones' },
  { name: 'Apricot', hex: '#FBCEB1', category: 'Warm Tones' },
  { name: 'Coral', hex: '#FF7F50', category: 'Warm Tones' },
  { name: 'Salmon', hex: '#FA8072', category: 'Warm Tones' },
  { name: 'Terracotta', hex: '#E2725B', category: 'Warm Tones' },
  { name: 'Burnt Sienna', hex: '#E97451', category: 'Warm Tones' },
  { name: 'Burnt Orange', hex: '#CC5500', category: 'Warm Tones' },
  { name: 'Rust', hex: '#B7410E', category: 'Warm Tones' },
  { name: 'Copper', hex: '#B87333', category: 'Warm Tones' },
  { name: 'Clay', hex: '#B66A50', category: 'Warm Tones' },
  { name: 'Pumpkin', hex: '#FF7518', category: 'Warm Tones' },

  { name: 'Light Red', hex: '#FF6B6B', category: 'Reds' },
  { name: 'Tomato', hex: '#FF6347', category: 'Reds' },
  { name: 'Scarlet', hex: '#FF2400', category: 'Reds' },
  { name: 'Brick Red', hex: '#CB4154', category: 'Reds' },
  { name: 'Burgundy', hex: '#800020', category: 'Reds' },
  { name: 'Crimson', hex: '#DC143C', category: 'Reds' },
  { name: 'Maroon', hex: '#800000', category: 'Reds' },
  { name: 'Cherry', hex: '#DE3163', category: 'Reds' },
  { name: 'Wine', hex: '#722F37', category: 'Reds' },
  { name: 'Ruby', hex: '#E0115F', category: 'Reds' },
  { name: 'Cranberry', hex: '#9F000F', category: 'Reds' },

  { name: 'Pale Yellow', hex: '#FFFFE0', category: 'Yellows' },
  { name: 'Butter Yellow', hex: '#FFFACD', category: 'Yellows' },
  { name: 'Lemon', hex: '#FFF44F', category: 'Yellows' },
  { name: 'Canary', hex: '#FFEF00', category: 'Yellows' },
  { name: 'Sunflower', hex: '#FFDA03', category: 'Yellows' },
  { name: 'Mustard', hex: '#FFDB58', category: 'Yellows' },
  { name: 'Gold', hex: '#FFD700', category: 'Yellows' },
  { name: 'Goldenrod', hex: '#DAA520', category: 'Yellows' },
  { name: 'Honey', hex: '#FFC30B', category: 'Yellows' },
  { name: 'Amber', hex: '#FFBF00', category: 'Yellows' },
  { name: 'Saffron', hex: '#F4C430', category: 'Yellows' },

  { name: 'Light Brown', hex: '#B5651D', category: 'Browns' },
  { name: 'Brown', hex: '#8B4513', category: 'Browns' },
  { name: 'Chestnut', hex: '#954535', category: 'Browns' },
  { name: 'Mahogany', hex: '#C04000', category: 'Browns' },
  { name: 'Auburn', hex: '#A52A2A', category: 'Browns' },
  { name: 'Espresso', hex: '#4E3629', category: 'Browns' },
  { name: 'Chocolate', hex: '#7B3F00', category: 'Browns' },
  { name: 'Coffee', hex: '#6F4E37', category: 'Browns' },
  { name: 'Walnut', hex: '#773F1A', category: 'Browns' },
  { name: 'Cinnamon', hex: '#D2691E', category: 'Browns' },
  { name: 'Caramel', hex: '#C68E17', category: 'Browns' },
  { name: 'Sienna', hex: '#A0522D', category: 'Browns' },

  { name: 'Pale Lavender', hex: '#F8E6F0', category: 'Purples' },
  { name: 'Lavender', hex: '#E6E6FA', category: 'Purples' },
  { name: 'Lilac', hex: '#C8A2C8', category: 'Purples' },
  { name: 'Mauve', hex: '#E0B0FF', category: 'Purples' },
  { name: 'Orchid', hex: '#DA70D6', category: 'Purples' },
  { name: 'Violet', hex: '#8F00FF', category: 'Purples' },
  { name: 'Purple', hex: '#800080', category: 'Purples' },
  { name: 'Plum', hex: '#8E4585', category: 'Purples' },
  { name: 'Grape', hex: '#6F2DA8', category: 'Purples' },
  { name: 'Eggplant', hex: '#614051', category: 'Purples' },
  { name: 'Amethyst', hex: '#9966CC', category: 'Purples' },

  { name: 'Light Pink', hex: '#FFB6C1', category: 'Pinks' },
  { name: 'Blush', hex: '#FFE4E1', category: 'Pinks' },
  { name: 'Rose', hex: '#FF007F', category: 'Pinks' },
  { name: 'Pink', hex: '#FFC0CB', category: 'Pinks' },
  { name: 'Dusty Rose', hex: '#DCAE96', category: 'Pinks' },
  { name: 'Magenta', hex: '#FF00FF', category: 'Pinks' },
  { name: 'Fuchsia', hex: '#FF00FF', category: 'Pinks' },
  { name: 'Hot Pink', hex: '#FF69B4', category: 'Pinks' },
  { name: 'Carnation', hex: '#FFA6C9', category: 'Pinks' },
  { name: 'Bubblegum', hex: '#FFC1CC', category: 'Pinks' },

  { name: 'Jet Black', hex: '#000000', category: 'Blacks' },
  { name: 'Onyx', hex: '#0F0F0F', category: 'Blacks' },
  { name: 'Ebony', hex: '#555D50', category: 'Blacks' },
  { name: 'Coal', hex: '#2B2B2B', category: 'Blacks' },
  { name: 'Raven', hex: '#1C1C1C', category: 'Blacks' },

  { name: 'Clear Glass', hex: '#E8F4F8', category: 'Glass' },
  { name: 'Ultra Clear', hex: '#F0F8FA', category: 'Glass' },
  { name: 'Frosted Glass', hex: '#F0F8FF', category: 'Glass' },
  { name: 'Frosted White', hex: '#F5F5F5', category: 'Glass' },
  { name: 'Satin Glass', hex: '#E8E8F0', category: 'Glass' },
  { name: 'Tinted Blue', hex: '#B8D8E8', category: 'Glass' },
  { name: 'Light Blue Tint', hex: '#D0E8F8', category: 'Glass' },
  { name: 'Ocean Blue', hex: '#A0C8E0', category: 'Glass' },
  { name: 'Sky Tint', hex: '#C8E0F0', category: 'Glass' },
  { name: 'Tinted Green', hex: '#C8E6D0', category: 'Glass' },
  { name: 'Light Green Tint', hex: '#D8F0E0', category: 'Glass' },
  { name: 'Sage Glass', hex: '#B8D8C8', category: 'Glass' },
  { name: 'Forest Tint', hex: '#A8C8B8', category: 'Glass' },
  { name: 'Tinted Gray', hex: '#D0D0D8', category: 'Glass' },
  { name: 'Light Gray Tint', hex: '#E0E0E8', category: 'Glass' },
  { name: 'Charcoal Glass', hex: '#B0B0B8', category: 'Glass' },
  { name: 'Stone Gray', hex: '#C0C0C8', category: 'Glass' },
  { name: 'Bronze Glass', hex: '#CD7F32', category: 'Glass' },
  { name: 'Light Bronze', hex: '#D89968', category: 'Glass' },
  { name: 'Antique Bronze', hex: '#B86F28', category: 'Glass' },
  { name: 'Copper Tint', hex: '#C88850', category: 'Glass' },
  { name: 'Smoke Glass', hex: '#848884', category: 'Glass' },
  { name: 'Light Smoke', hex: '#A0A0A8', category: 'Glass' },
  { name: 'Dark Smoke', hex: '#606068', category: 'Glass' },
  { name: 'Black Smoke', hex: '#404048', category: 'Glass' },
  { name: 'Dark Tinted', hex: '#4A4A4A', category: 'Glass' },
  { name: 'Privacy Glass', hex: '#606060', category: 'Glass' },
  { name: 'Reflective Silver', hex: '#C0C0C0', category: 'Glass' },
  { name: 'Mirror Glass', hex: '#B8B8C0', category: 'Glass' },
  { name: 'Reflective Gold', hex: '#D4AF37', category: 'Glass' },
  { name: 'Reflective Blue', hex: '#A8C8D8', category: 'Glass' },
  { name: 'Aqua Glass', hex: '#7FDBFF', category: 'Glass' },
  { name: 'Turquoise Glass', hex: '#40E0D0', category: 'Glass' },
  { name: 'Teal Glass', hex: '#008080', category: 'Glass' },
  { name: 'Amber Glass', hex: '#FFBF00', category: 'Glass' },
  { name: 'Light Amber', hex: '#FFD700', category: 'Glass' },
  { name: 'Dark Amber', hex: '#E09F00', category: 'Glass' },
  { name: 'Rose Glass', hex: '#FFB3BA', category: 'Glass' },
  { name: 'Pink Glass', hex: '#FFD0D8', category: 'Glass' },
  { name: 'Blush Glass', hex: '#FFE0E8', category: 'Glass' },
  { name: 'Purple Tint', hex: '#D8C8E8', category: 'Glass' },
  { name: 'Lavender Glass', hex: '#E0D0F0', category: 'Glass' },
  { name: 'Yellow Tint', hex: '#F8F0C8', category: 'Glass' },
  { name: 'Champagne Glass', hex: '#F7E7CE', category: 'Glass' },
  { name: 'Opal Glass', hex: '#E8F0F8', category: 'Glass' },
  { name: 'Pearl Glass', hex: '#F0F0E8', category: 'Glass' },

  { name: 'Mint Cream', hex: '#F5FFFA', category: 'Pastels' },
  { name: 'Pale Peach', hex: '#FFDAB9', category: 'Pastels' },
  { name: 'Pale Mint', hex: '#C1FFC1', category: 'Pastels' },
  { name: 'Pale Coral', hex: '#FFA07A', category: 'Pastels' },
  { name: 'Pale Sky', hex: '#C1E1EC', category: 'Pastels' },
  { name: 'Pale Rose', hex: '#FFC0CB', category: 'Pastels' },
  { name: 'Pale Lavender', hex: '#E6E6FA', category: 'Pastels' },
  { name: 'Pale Lemon', hex: '#FFFACD', category: 'Pastels' },

  { name: 'Deep Navy', hex: '#000033', category: 'Deep Tones' },
  { name: 'Deep Forest', hex: '#0B4F0F', category: 'Deep Tones' },
  { name: 'Deep Burgundy', hex: '#4A0E0E', category: 'Deep Tones' },
  { name: 'Deep Teal', hex: '#003B3B', category: 'Deep Tones' },
  { name: 'Deep Purple', hex: '#301934', category: 'Deep Tones' },
  { name: 'Deep Brown', hex: '#3E2723', category: 'Deep Tones' },

  { name: 'Bright Red', hex: '#FF0000', category: 'Bright Colors' },
  { name: 'Bright Blue', hex: '#0000FF', category: 'Bright Colors' },
  { name: 'Bright Green', hex: '#00FF00', category: 'Bright Colors' },
  { name: 'Bright Yellow', hex: '#FFFF00', category: 'Bright Colors' },
  { name: 'Bright Orange', hex: '#FF8C00', category: 'Bright Colors' },
  { name: 'Bright Pink', hex: '#FF1493', category: 'Bright Colors' },
  { name: 'Bright Cyan', hex: '#00FFFF', category: 'Bright Colors' },

  { name: 'Muted Olive', hex: '#6B7F4F', category: 'Muted Tones' },
  { name: 'Muted Rose', hex: '#C08081', category: 'Muted Tones' },
  { name: 'Muted Blue', hex: '#5D7A8C', category: 'Muted Tones' },
  { name: 'Muted Gold', hex: '#B8945C', category: 'Muted Tones' },
  { name: 'Muted Teal', hex: '#5B8A8A', category: 'Muted Tones' },
  { name: 'Muted Lavender', hex: '#9B8FA9', category: 'Muted Tones' },
];

export const COLOR_CATEGORIES = [
  'All',
  'Whites',
  'Neutrals',
  'Grays',
  'Blues',
  'Greens',
  'Warm Tones',
  'Reds',
  'Yellows',
  'Browns',
  'Purples',
  'Pinks',
  'Blacks',
  'Glass',
  'Pastels',
  'Deep Tones',
  'Bright Colors',
  'Muted Tones',
];
